[workspace]
resolver = "2"
members = ["crates/*", "examples/rustywallet-checker-demo", "examples/rustywallet-generator-demo", "examples/rustywallet-batch-demo"]

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/nirvagold/rustywallet"
authors = ["nirvagold <nirvagold@gmail.com>"]

[workspace.dependencies]
# Crypto
secp256k1 = { version = "0.29", features = ["rand", "global-context"] }

# Encoding
bs58 = "0.5"
sha2 = "0.10"

# Utils
rand = "0.8"
zeroize = { version = "1.8", features = ["derive"] }
thiserror = "1.0"

# Dev dependencies
proptest = "1.5"
